version: "3.5"

services:
  auth:
    image: 015331741/msit-devops-cluster-auth:latest
    ports:
      - 5000:5000
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
  shop:
    image: 015331741/msit-devops-cluster-shop:latest
    ports:
      - 4000:4000
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
  product:
    image: 015331741/msit-devops-cluster-product:latest
    ports:
      - 3000:3000
    deploy:
      mode: global
      # replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
