name: Build and Push Docker Images

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, shop, product]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract tag version # Extract the version from the tag without leading 'v'
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }} service
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/msit-devops-cluster-${{ matrix.service }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/msit-devops-cluster-${{ matrix.service }}:${{ steps.version.outputs.VERSION }}
